use_frameworks!

platform :ios, '8.0'

target 'AMKPromptView_Example' do
  pod 'AMKPromptView', :path => '../'
  pod 'YYCategories'
  pod 'YPNavigationBarTransition'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) COCOAPODS=1 AMKPV_SHORTHAND_GLOBALS=1'
    end
  end
end
